"""change status to string

Revision ID: 218b4274cd91
Revises: 311e42519119
Create Date: 2026-03-05 00:12:13.852284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "218b4274cd91"
down_revision: Union[str, Sequence[str], None] = "311e42519119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade() -> None:
        op.alter_column(
            "events",
            "status",
            type_=sa.String(50),
            postgresql_using="status::text",
        )
        op.execute("DROP TYPE IF EXISTS eventstatus")

    def downgrade() -> None:
        op.execute("CREATE TYPE eventstatus AS ENUM ('registration_closed', 'published')")
        op.alter_column(
            "events",
            "status",
            type_=sa.Enum("registration_closed", "published", name="eventstatus"),
            postgresql_using="status::eventstatus",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("ticket_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("seat", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("tickets_event_id_fkey")
        ),
        sa.PrimaryKeyConstraint("ticket_id", name=op.f("tickets_pkey")),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("seats_pattern", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "changed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("places_pkey")),
    )
    op.create_table(
        "sync_metadata",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "last_sync_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_changed_at", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sync_status", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_metadata_pkey")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("place_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "event_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "registration_deadline",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("registration_closed", "published", name="eventstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "number_of_visitors", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "changed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status_changed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.id"], name=op.f("events_place_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("events_pkey")),
    )
    # ### end Alembic commands ###
